// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxkupyqctbgsbcgpmdbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4a3VweXFjdGJnc2JjZ3BtZGJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMzk4NjEsImV4cCI6MjA2MTcxNTg2MX0.o3NZtTzOgENCCbltBBaSJcV-vgroFePCkrMQzCQzAEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);