// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhenrtzbutqjymgykkhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oZW5ydHpidXRxanltZ3lra2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNjYzMDQsImV4cCI6MjA2Mjc0MjMwNH0.qfAYyXT5gyGpyVOfC1VkLCTJ0g1-x13_AeboFQGUxi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);